# Generated by Django 4.0 on 2022-08-31 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
    ]
