# Generated by Django 4.0 on 2022-09-02 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_audio_audio_base64_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='audio_base64',
            field=models.CharField(max_length=130000, null=True),
        ),
    ]
