# Generated by Django 4.0 on 2022-09-02 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_alter_audio_audio_base64'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDevices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=150)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='audio',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
