# Generated by Django 4.0 on 2022-09-02 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_clientdevices_audio_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdevices',
            name='is_active',
            field=models.CharField(default=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='clientdevices',
            name='is_approved',
            field=models.CharField(default=False, max_length=50),
        ),
    ]
