# Generated by Django 4.0 on 2022-09-02 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_alter_clientdevices_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdevices',
            name='is_active',
            field=models.CharField(default='Inactive', max_length=50),
        ),
        migrations.AlterField(
            model_name='clientdevices',
            name='is_approved',
            field=models.CharField(default='Unapproved', max_length=50),
        ),
    ]
