# Generated by Django 4.0 on 2022-09-02 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_alter_clientdevices_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdevices',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='clientdevices',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
