# Generated by Django 4.0 on 2022-09-05 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_alter_clientdevices_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdevices',
            name='last_req_time',
            field=models.TimeField(auto_now=True),
        ),
    ]
