# Generated by Django 4.0 on 2022-09-05 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0010_alter_clientdevices_last_req_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientdevices',
            name='last_req_time',
        ),
    ]
