# Generated by Django 4.0 on 2022-09-05 17:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0013_alter_clientdevices_last_req_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdevices',
            name='last_req_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 5, 17, 4, 41, 74105)),
        ),
    ]
